In [2]:
import pandas as pd
import random

mosi = pd.read_csv("raw_data/mosi/new_MOSI-label-v5.csv")
mosi_df = mosi[['text' , 'annotation', 'score_label']].copy()
mosi_df.rename(columns = {'text':'text', 'annotation':'sentiment',
                              'score_label':'score'}, inplace = True)
# mosi_df = mosi_df.sample(n=1000)
mosi_df.to_csv('raw_data//mosi/mosi.csv', index=False)

In [3]:
import pandas as pd
import random

mosei = pd.read_csv("raw_data/mosei/new_MOSEI-label-v5.csv")
mosei_df = mosei[['text', 'annotation', 'score_label']].copy()
mosei_df.rename(columns = {'text':'text', 'annotation':'sentiment',
                              'score_label':'score'}, inplace = True)
# mosei_df = mosei_df.sample(n=1000)
mosei_df.to_csv('raw_data/mosei/mosei.csv', index= False)

In [6]:
import pandas as pd
import random

meld = pd.read_csv("raw_data/meld/all_sent_emo.csv")
meld_df = meld[['Utterance', 'Emotion', 'Sentiment']].copy()
meld_df.rename(columns = {'Utterance':'text', 'Emotion':'meld',
                              'Sentiment':'sentiment'}, inplace = True)
# meld_df = meld_df.sample(n=1000)
meld_df.to_csv('raw_data/meld/meld.csv', index=False)

In [5]:
import pandas as pd
import random

iemocap = pd.read_csv("raw_data/iemocap/new-iemocap-label-v5-contexts.csv")
iemocap_df = iemocap[['text', 'label']].copy()
iemocap_df.rename(columns = {'text':'text', 'label':'iemocap'}, inplace = True)
# iemocap_df = iemocap_df.sample(n=1000)
iemocap_df.to_csv('raw_data/iemocap/iemocap_context.csv', index=False)

MOSI

In [1]:
import pickle as pkl
import pandas as pd
with open("datasets/MOSI/train_align_0610.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
# features  = df[0][0]
# texts = features[3]
# print(texts)
df
# df.to_csv('iemocap_0610.csv')

0  \
0     ([], [[-0.18592529, -0.634137, 0.3674638, -0.3...   
1     ([], [[-0.13318847, -0.63599545, 0.47709018, -...   
2     ([], [[-0.17779551, -0.6122902, 0.24020892, -0...   
3     ([], [[-0.12196843, -0.69122815, 0.37146524, -...   
4     ([], [[-0.18493757, -0.6653232, 0.12956809, -0...   
...                                                 ...   
1279  ([], [[0.05613606, -0.34698528, 0.6250884, -0....   
1280  ([], [[0.052146833, -0.33682337, 0.6712408, -0...   
1281  ([], [[-0.013101313, -0.37124246, 0.5847913, -...   
1282  ([], [[-0.008766029, -0.3605447, 0.56967723, -...   
1283  ([], [[0.006112974, -0.30531302, 0.6098187, -0...   

                                  1               2  
0     negative,-0.5,neutral,neutral  03bSnISJMiM_11  
1         negative,-1.2,sadness,sad  03bSnISJMiM_10  
2              positive,1.8,joy,hap  03bSnISJMiM_13  
3              positive,2.2,joy,exc  03bSnISJMiM_12  
4              positive,2.4,joy,hap   03bSnISJMiM_1  
...                             ...             ...  
1279     negative,-0.75,sadness,fru  W8NXH0Djyww_19  
1280           positive,2.2,joy,hap  W8NXH0Djyww_18  
1281           positive,0.6,joy,hap  W8NXH0Djyww_31  
1282        negative,-0.4,anger,sad  W8NXH0Djyww_30  
1283      positive,2.0,surprise,exc  W8NXH0Djyww_32  

[1284 rows x 3 columns]

In [5]:
import pandas as pd
df = pd.read_csv('datasets/MOSI/MOSI/new_MOSI-label-v5.csv')
print(df['iemocap_label'].unique())

['neutral' 'sad' 'hap' 'exc' 'ang' 'fru' 'dis' 'sur' 'fea']


MOSEI

In [2]:
import pickle as pkl
import pandas as pd
with open("datasets/MOSEI/train_align_0610.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
# features  = df[0][0]
# texts = features[3]
# print(texts)
df
# df.to_csv('iemocap_0610.csv')

0  \
0      ([], [[0.40541595, 0.76268375, 0.6046679, 0.46...   
1      ([], [[0.3952484, 0.7394676, 0.63508743, 0.464...   
2      ([], [[0.44244385, 0.87012315, 0.58410496, 0.4...   
3      ([], [[0.34089577, 0.95235395, 0.65393615, 0.5...   
4      ([], [[0.38717517, 0.8767146, 0.6403049, 0.455...   
...                                                  ...   
16321  ([], [[0.14024659, 0.55750823, 0.711234, 0.066...   
16322  ([], [[0.15048273, 0.5483283, 0.57876736, 0.03...   
16323  ([], [[0.15316615, 0.505311, 0.578016, 0.07692...   
16324  ([], [[0.28253597, 0.5794093, 0.87073547, 0.15...   
16325  ([], [[0.58491284, 0.7688454, 0.31724235, 0.41...   

                                     1            2  
0                 positive,1.0,joy,exc  -3g5yACwYnA  
1      positive,0.6666667,surprise,exc  -3g5yACwYnA  
2          neutral,0.0,neutral,neutral  -3g5yACwYnA  
3          neutral,0.0,neutral,neutral  -3g5yACwYnA  
4                 positive,1.0,joy,exc  -3g5yACwYnA  
...                                ...          ...  
16321      neutral,0.0,neutral,neutral  zwTrXwi54us  
16322      neutral,0.0,neutral,neutral  zwTrXwi54us  
16323       positive,0.6666667,joy,exc  zwTrXwi54us  
16324             positive,1.0,joy,hap  zwTrXwi54us  
16325             positive,1.0,joy,exc  zx4W0Vuus-I  

[16326 rows x 3 columns]

MELD

In [1]:
import pickle as pkl
import pandas as pd
with open("datasets/MELD/train_align_0610.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
# features  = df[0][0]
# texts = features[3]
# print(texts)
df
# df.to_csv('iemocap_0610.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MELD/train_align_0610.pkl'

IEMOCAP

In [4]:
import pickle as pkl
import pandas as pd
with open("datasets/IEMOCAP/train_align_0610.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
# features  = df[0][0]
# texts = features[3]
# print(texts)
df
# df.to_csv('iemocap_0610.csv')

0  \
0     (None, [[-0.5668003, 0.56486267, 0.036618523, ...   
1     (None, [[-0.584269, 0.6170926, 0.031836115, 0....   
2     (None, [[-0.51869637, 0.47913355, 0.104346, 0....   
3     (None, [[-0.583243, 0.53865707, 0.09574469, 0....   
4     (None, [[-0.6217078, 0.541157, 0.15852138, 0.4...   
...                                                 ...   
5232  (None, [[-0.8666882, 0.12713343, 0.5530417, 0....   
5233  (None, [[-0.8573355, 0.19597177, 0.50460213, 0...   
5234  (None, [[-0.82451844, 0.20689747, 0.48602784, ...   
5235  (None, [[-0.8332093, 0.18813212, 0.5214094, 0....   
5236  (None, [[-0.7984799, 0.32891333, 0.49789894, 0...   

                                             1                       2  
0                      neutral,0.0,neutral,neu     Ses01F_impro01_F000  
1                      neutral,0.0,neutral,neu     Ses01F_impro01_F001  
2                      neutral,0.0,neutral,neu     Ses01F_impro01_F002  
3                      neutral,0.0,neutral,neu     Ses01F_impro01_F005  
4       negative,-0.6666666865348816,anger,fru     Ses01F_impro01_F006  
...                                        ...                     ...  
5232    negative,-0.3333333432674408,anger,ang  Ses04M_script03_2_M052  
5233                   negative,-2.0,anger,ang  Ses04M_script03_2_M053  
5234                 negative,-1.0,disgust,ang  Ses04M_script03_2_M054  
5235  negative,-0.3333333432674408,sadness,ang  Ses04M_script03_2_M055  
5236  negative,-0.6666666865348816,sadness,ang  Ses04M_script03_2_M056  

[5237 rows x 3 columns]

MOSELDMP

In [50]:
# datasets/MOSELDMP/new_moseldmp_train_align_v4_0610_a_6c_contexts.pkl
import pickle as pkl
import pandas as pd
with open("datasets/MOSELDMP/new_moseldmp_train_align_v4_0610_a_6c_contexts.pkl", "rb") as f:
    object = pkl.load(f)
    
df = pd.DataFrame(object)
# features  = df[0][0]
# texts = features[3]
# print(texts)
df
# df.to_csv('iemocap_0610.csv')

0  \
0   (None, [[-0.56617874, 0.10630635, 0.31532407, ...   
1   (None, [[-0.6038785, 0.5497486, 0.2703596, 0.2...   
2   (None, [[-0.5047961, 0.3021077, 0.40092304, 0....   
3   ([], [[0.16840526, 0.4089079, 0.46344382, 0.30...   
4   (None, [[-0.48876336, 0.4457317, 0.16329643, 0...   
..                                                ...   
74  ([], [[0.32726266980171204, -0.547826647758483...   
75  ([], [[-0.17984308302402496, -0.15328437089920...   
76  ([], [[0.156732, 0.3222466, 0.30848914, 0.2111...   
77  (None, [[-0.51575834, 0.29811087, 0.15066369, ...   
78  (None, [[-0.48789403, 0.7958722, 0.13605359, 0...   

                                               1                       2  
0                    neutral,0.0,neutral,neutral                  665_12  
1                    neutral,0.0,neutral,sadness  Ses01M_script01_1_M024  
2              negative,-1.0,surprise,frustrated    Ses03M_impro08a_F031  
3                 positive,0.6666667,joy,excited                   94983  
4   negative,-2.3333332538604736,sadness,sadness     Ses01F_impro06_F007  
..                                           ...                     ...  
74                          positive,1.6,joy,joy          8d-gEyoeBzc_19  
75                 positive,0.6,surprise,excited          BXuRRbG0Ugk_13  
76                positive,1.3333334,joy,excited             RS5WM3q2ZZQ  
77                   neutral,0.0,neutral,neutral                   933_7  
78       positive,0.3333333432674408,joy,excited     Ses04F_impro03_F002  

[79 rows x 3 columns]

In [ ]:
"""
Pickle2JSON is a simple Python Command Line program for converting Pickle file to JSON file.
Arguments: Only one (1) argument is expected which is the pickle file.
Usage: python pickle2json.py myfile.pkl
Output: The output is a JSON file bearing the same filename containing the JSON document of the converted Pickle file.
"""

# import libraries
import pickle
import json
import sys
import os

# open pickle file
with open('datasets/IEMOCAP/new_dev_por_v4_0610_6c_sep_contexts.pkl', 'rb') as infile:
    obj = pickle.load(infile)

# convert pickle object to json object
json_obj = json.loads(json.dumps(obj, default=str))

# write the json file
with open(
        'iemocap_0610_sep_context.json',
        'w',
        encoding='utf-8'
    ) as outfile:
    json.dump(json_obj, outfile, ensure_ascii=False, indent=4)

In [45]:
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        pass

    try:
        import unicodedata
        unicodedata.numeric(s)
        return True
    except (TypeError, ValueError):
        pass

    return False

# def pre_gen(results):
#             #保障生成格式
#             new_results = []
#             for ele in results:
#                 if len(str(ele).split(','))==1:
#                     if is_number(str(ele)):
#                         new_results.append(str(ele)+','+'neutral')
#                     else:
#                         new_results.append('0.0'+','+str(ele))
#                 else:
#                     new_results.append(ele)
                    
#             return new_results

def pre_gen(results):
            #保障生成格式
            new_results = []
            for ele in results:
                if len(str(ele).split(','))==1:
                    if is_number(str(ele)):
                        new_results.append(str(ele)+','+'neutral,neutral,neutral')
                    else:
                        new_results.append('0.0'+','+str(ele) +',neutral,neutral')
                elif len(str(ele).split(','))==2:
                    new_results.append(str(ele)+','+'neutral' +',' + 'neutral')
                elif len(str(ele).split(','))==3:
                    new_results.append(str(ele)+','+'neutral')
                else:
                    new_results.append(ele)
                    
            return new_results

results = ['0.0', 'positive,joy', 'positive,0.0,joy', 'positive,0.0,joy,neutral']
new_res = pre_gen(results)
print(new_res)

['0.0,neutral,neutral,neutral', 'positive,joy,neutral,neutral', 'positive,0.0,joy,neutral', 'positive,0.0,joy, neutral']


In [75]:
# Python program to find transpose of a 2D tensor
# import torch library
def transpose(x):
    return x.transpose(-2, -1)

import torch

# define a 2D tensor
query = torch.rand(3, 30)
print(query)
# tran = query.transpose(1, 2)
# print(tran.size())
# print(tran.shape[-1])
positive_key = torch.rand(3, 30)
print(positive_key)
# pos_tran = transpose(positive_key)
# print(pos_tran.size())
# logits = query @ transpose(positive_key)
# print(logits.size())

# print(positive_key)
positive_logit = torch.sum(query * positive_key, dim=1, keepdim=True)
print(positive_logit)
# # compute the transpose of the above tensor
# print(A.t())
# # or print(torch.t(A))

# print(A.transpose(1, 2))
# # or print(torch.transpose(A, 0, 1))

tensor([[0.2962, 0.4906, 0.9217, 0.8928, 0.0933, 0.4259, 0.2086, 0.7997, 0.5497,
         0.0854, 0.6266, 0.1130, 0.5439, 0.8149, 0.1135, 0.2199, 0.1579, 0.6425,
         0.6687, 0.3492, 0.3943, 0.8004, 0.9458, 0.0276, 0.7236, 0.0586, 0.9963,
         0.8664, 0.2408, 0.7702],
        [0.0133, 0.6261, 0.6629, 0.4890, 0.4426, 0.1712, 0.7481, 0.6617, 0.5009,
         0.7890, 0.3411, 0.3125, 0.9982, 0.7041, 0.2739, 0.4562, 0.9019, 0.2639,
         0.4609, 0.1628, 0.6538, 0.7714, 0.6700, 0.6337, 0.8468, 0.9991, 0.3560,
         0.8286, 0.6748, 0.7432],
        [0.8743, 0.1979, 0.5215, 0.7333, 0.4093, 0.0498, 0.8169, 0.1714, 0.3403,
         0.0365, 0.8771, 0.7837, 0.7896, 0.1604, 0.3240, 0.9421, 0.4571, 0.9280,
         0.2019, 0.3807, 0.1553, 0.5128, 0.4767, 0.3868, 0.5313, 0.6320, 0.6013,
         0.4529, 0.2842, 0.2526]])
tensor([[0.8476, 0.7172, 0.6614, 0.1408, 0.1804, 0.3144, 0.4396, 0.8997, 0.4569,
         0.8440, 0.9765, 0.5242, 0.1937, 0.1549, 0.2234, 0.0502, 0.5532, 0.6084,
      

In [73]:
import torch

positive_logit = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(positive_logit.size())
negative_logits = torch.tensor([[4, 5, 6], [7, 8, 9]])
print(negative_logits.size())
proj_query = torch.mean(positive_logit, dim=-1)
print("mean projection query size", proj_query)
# result = torch.cat([positive_logit, negative_logits], dim=1)
# print(result)


torch.Size([2, 3])
torch.Size([2, 3])
mean projection query size tensor([2., 5.])
tensor([[ 1,  2,  3,  4,  5,  6],
        [-2, -3, -2,  7,  8,  9]])


In [79]:
import pandas as pd 
data = pd.read_csv('datasets/IEMOCAP/IEMOCAP/new-iemocap-label-v4-contexts.csv')
for i in range(data.shape[0]):
    line = data.iloc[i]
    label = line['label']
    if label == 'neu':
        data.at[i, 'por'] = 'neutral'
    elif label in ['hap', 'exc']:
        data.at[i, 'por']= 'positive'
    else:
        data.at[i, 'por'] = 'negative'
data.to_csv('datasets/IEMOCAP/IEMOCAP/new-iemocap-label-v5-contexts.csv')